import assert from 'node:assert/strict';
import{localCities,mergeCities,searchCities,locateCity,cityFromLocation,latestRequest}from '../dist/js/city-data.js';
const tyumen=localCities('Тю')[0];assert.equal(tyumen.name,'Тюмень');assert.equal(tyumen.timezone,'Asia/Yekaterinburg');assert.equal(localCities('ме')[0].name,'Медина');assert.deepEqual(localCities('Т'),[]);
const existing={name:'Тюкалинск',latitude:55.873,longitude:72.196,timezone:'Asia/Omsk',country:'Россия'};assert.ok(localCities('Тю',existing).some(c=>c.name==='Тюкалинск'));
assert.equal(mergeCities([tyumen],[{...tyumen,latitude:tyumen.latitude+.005}]).length,1);assert.equal(mergeCities([tyumen],[{...tyumen,latitude:10}]).length,2);assert.equal(mergeCities([{...tyumen,timezone:'not-a-timezone'},{...tyumen,latitude:100}]).length,0);
let urls=[];const search=await searchCities('Тюм',{fetcher:async(url,options)=>{urls.push(String(url));assert.equal(options.credentials,'omit');return {ok:true,json:async()=>({results:[tyumen,{name:'bad'}]})}}});assert.equal(search.length,1);assert.equal(new URL(urls[0]).searchParams.get('name'),'Тюм');
// These are local test doubles only: no external reverse request uses fictional/stored GPS.
const coords={latitude:57.150123,longitude:65.520987};const located=await locateCity(coords,{fetcher:async url=>{urls.push(String(url));return {ok:true,json:async()=>String(url).includes('bigdatacloud')?{city:'Тюмень',countryName:'Россия'}:{timezone:'Asia/Yekaterinburg'}}}});assert.equal(located.name,'Тюмень');assert.equal(located.latitude,coords.latitude);assert.equal(located.longitude,coords.longitude);assert.equal(located.timezone,'Asia/Yekaterinburg');
assert.equal(cityFromLocation({locality:'Село'}, {timezone:'Asia/Omsk'},coords).name,'Село');assert.equal(cityFromLocation({}, {timezone:'Asia/Omsk'},coords),null);assert.equal(cityFromLocation({city:'Медина'}, {timezone:'Invalid'},coords),null);
await assert.rejects(locateCity(coords,{fetcher:async()=>({ok:false})}));await assert.rejects(locateCity({latitude:NaN,longitude:5},{fetcher:()=>{throw Error('Should not fetch invalid position')}}));
const queue=latestRequest(),first=queue.start(),second=queue.start();assert.equal(first.signal.aborted,true);assert.equal(first.current(),false);assert.equal(second.current(),true);queue.cancel();assert.equal(second.current(),false);const third=queue.start();assert.equal(third.current(),true);
console.log('PASS: two-letter city suggestions, selected-city matching, deduplication, remote validation, precise GPS with correct city timezone, failed lookup, stale/cancelled requests.');
