import assert from 'node:assert/strict';
import{localCities,mergeCities,searchCities,locateCity,cityFromLocation,latestRequest}from '../dist/js/city-data.js';
const tyumen=localCities('Тю').find(city=>city.name==='Тюмень'&&city.timezone==='Asia/Yekaterinburg');assert.ok(localCities('Тю').some(city=>city.name==='Тюкалинск'),'Two letters cannot suggest only Tyumen');assert.ok(localCities('Тю').filter(city=>city.name==='Тюмень').length>1,'Homonymous settlements are kept');assert.equal(tyumen.name,'Тюмень');assert.equal(tyumen.timezone,'Asia/Yekaterinburg');assert.equal(localCities('ме')[0].name,'Медина');assert.deepEqual(localCities('Т'),[]);
assert.equal(cityFromLocation({city:'городской округ Тюмень',locality:'Центральный район'}, {timezone:'Asia/Yekaterinburg'},{latitude:57.15,longitude:65.52}).name,'Тюмень');
assert.equal(cityFromLocation({city:'городской округ Тюмень',locality:'Каскара'}, {timezone:'Asia/Yekaterinburg'},{latitude:57.2,longitude:65.7}).name,'Каскара','A village name wins over its encompassing district');
assert.equal(cityFromLocation({city:'Тюменский муниципальный округ',locality:'Каскара'}, {timezone:'Asia/Yekaterinburg'},{latitude:57.2,longitude:65.7}).name,'Каскара');
assert.equal(cityFromLocation({city:'Тюменский район',locality:'Центральный район',localityInfo:{informative:[{name:'Тюмень',description:'City'}]}}, {timezone:'Asia/Yekaterinburg'},{latitude:57.15,longitude:65.52}).name,'Тюмень');
assert.equal(cityFromLocation({city:'Тюменская область',locality:'Тюменский округ'}, {timezone:'Asia/Yekaterinburg'},{latitude:57.15,longitude:65.52}),null,'A district alone cannot masquerade as a city');
const existing={name:'Тюкалинск',latitude:55.873,longitude:72.196,timezone:'Asia/Omsk',country:'Россия'};assert.ok(localCities('Тю',existing).some(c=>c.name==='Тюкалинск'));
assert.equal(mergeCities([tyumen],[{...tyumen,latitude:tyumen.latitude+.005}]).length,1);assert.equal(mergeCities([tyumen],[{...tyumen,latitude:10}]).length,2);assert.equal(mergeCities([{...tyumen,timezone:'not-a-timezone'},{...tyumen,latitude:100}]).length,0);
let urls=[];const search=await searchCities('Тюм',{fetcher:async(url,options)=>{urls.push(String(url));assert.equal(options.credentials,'omit');return {ok:true,json:async()=>({results:[tyumen,{name:'bad'}]})}}});assert.equal(search.length,1);assert.equal(new URL(urls[0]).searchParams.get('name'),'Тюм');
// These are local test doubles only: no external reverse request uses fictional/stored GPS.
const sameName=await searchCities('Тюмень',{fetcher:async()=>({ok:true,json:async()=>({results:[tyumen,{...tyumen,latitude:58.41553,longitude:49.23639,timezone:'Europe/Kirov',admin1:'Кировская область'}]})})});assert.equal(sameName.length,2);assert.notEqual(sameName[0].timezone,sameName[1].timezone,'Names alone cannot merge distinct cities');
const coords={latitude:57.150123,longitude:65.520987};const located=await locateCity(coords,{fetcher:async url=>{urls.push(String(url));return {ok:true,json:async()=>String(url).includes('bigdatacloud')?{city:'Тюмень',countryName:'Россия'}:{timezone:'Asia/Yekaterinburg'}}}});assert.equal(located.name,'Тюмень');assert.equal(located.latitude,coords.latitude);assert.equal(located.longitude,coords.longitude);assert.equal(located.timezone,'Asia/Yekaterinburg');
assert.equal(cityFromLocation({locality:'Село'}, {timezone:'Asia/Omsk'},coords).name,'Село');assert.equal(cityFromLocation({}, {timezone:'Asia/Omsk'},coords),null);assert.equal(cityFromLocation({city:'Медина'}, {timezone:'Invalid'},coords),null);
await assert.rejects(locateCity(coords,{fetcher:async()=>({ok:false})}));await assert.rejects(locateCity({latitude:NaN,longitude:5},{fetcher:()=>{throw Error('Should not fetch invalid position')}}));
const queue=latestRequest(),first=queue.start(),second=queue.start();assert.equal(first.signal.aborted,true);assert.equal(first.current(),false);assert.equal(second.current(),true);queue.cancel();assert.equal(second.current(),false);const third=queue.start();assert.equal(third.current(),true);
console.log('PASS: two-letter city suggestions, selected-city matching, deduplication, remote validation, precise GPS with correct city timezone, failed lookup, stale/cancelled requests.');
