// Generated by scripts/build-push-function.mjs; edit core.mjs and runtime.txt.
import postgres from 'npm:postgres@3.4.9';
import webpush from 'npm:web-push@3.6.7';

// Shared by the web timetable and the background reminder service.
const TYUMEN_SOURCES=['auto','calendar','al-hakk'];
function normalizeTyumenSource(value){return TYUMEN_SOURCES.includes(value)?value:'auto'}
function tyumenSourceFiles(value){
 const source=normalizeTyumenSource(value);
 return source==='calendar'?['tyumen-october-2026.json']:source==='al-hakk'?['al-hakk-tyumen.json']:['al-hakk-tyumen.json','tyumen-october-2026.json'];
}
function matchesTyumenSource(value,row){
 const source=normalizeTyumenSource(value);
 return source==='auto'||row?.source===(source==='calendar'?'tyumen-table':'al-hakk');
}

// The first Asr supplements the published Hanafi time; it never replaces it.
const firstAsrSourceUrl='https://aladhan.com/prayer-times-api';
function firstAsrValid(day,row,time){
  if(typeof time!=='string'||!time.startsWith(day+'T')||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:00\+05:00$/.test(time))return false;
  const stamp=Date.parse(time),noon=Date.parse(row?.timings?.Dhuhr),sunset=Date.parse(row?.timings?.Maghrib);
  return Number.isFinite(stamp)&&Number.isFinite(noon)&&Number.isFinite(sunset)&&stamp>noon&&stamp<sunset;
}
function parseFirstAsrCalendar(json,month){
  if(json?.code!==200||!Array.isArray(json.data))throw Error('Некорректный ответ расчёта Асра');
  const result={};
  for(const row of json.data){
    const date=row.date?.gregorian?.date;
    if(!/^\d{2}-\d{2}-\d{4}$/.test(date||''))continue;
    const day=date.split('-').reverse().join('-'),meta=row.meta;
    if(day.slice(0,7)!==month||meta?.school!=='STANDARD'||meta.timezone!=='Asia/Yekaterinburg'||Number(meta.method?.id)!==3||Math.abs(Number(meta.latitude)-57.1522)>0.0001||Math.abs(Number(meta.longitude)-65.5272)>0.0001||!Number.isFinite(Number(meta.latitude))||!Number.isFinite(Number(meta.longitude)))continue;
    if(firstAsrValid(day,row,row.timings?.Asr))result[day]={time:row.timings.Asr,source:'Aladhan · расчёт',sourceUrl:firstAsrSourceUrl,kind:'calculated'};
  }
  return result;
}
function mergeFirstAsr(days,supplement){
  const result={...days};
  for(const [day,row]of Object.entries(days)){
    if(row.source!=='al-hakk'||firstAsrValid(day,row,row.asrFirst))continue;
    const first=supplement?.[day];
    if(first?.kind==='calculated'&&firstAsrValid(day,row,first.time))result[day]={...row,asrFirst:first.time,asrFirstSource:first.source,asrFirstSourceUrl:first.sourceUrl,asrFirstKind:'calculated'};
  }
  return result;
}

const minute=60000;
function personalTime(value){return typeof value==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(value)?value:''}
// Timestamps carry the city's offset: no device timezone or fixed 24-hour night.
function lastThirdNight(maghrib,fajr){
  if(!Number.isFinite(maghrib)||!Number.isFinite(fajr))return null;
  const duration=fajr-maghrib;
  if(duration<=0||duration>=24*60*minute)return null;
  // Round forward so the displayed minute is already within the last third.
  const time=Math.ceil((maghrib+duration*2/3)/minute)*minute;
  return time<fajr?time:null;
}
function tahajjudFor(now,{previous,today,next}={},chosenTime=''){
  const text=personalTime(chosenTime);
  if(text)return {kind:'manual',text,label:'Личное время'};
  if(!Number.isFinite(now)||!Number.isFinite(today?.Fajr))return null;
  const beforeFajr=now<today.Fajr;
  const nightStart=beforeFajr?previous?.Maghrib:today?.Maghrib;
  const nightEnd=beforeFajr?today.Fajr:next?.Fajr;
  const time=lastThirdNight(nightStart,nightEnd);
  return time===null?null:{kind:'last-third',time,nightStart,nightEnd,label:'Начало последней трети ночи'};
}

// Short excerpts; the hadith wording below is a Russian rendering of its meaning.
const DHIKR_MESSAGES=[
 {text:'«Поминайте Меня, и Я буду помнить о вас». Коран, 2:152.',source:'https://quran.com/ru/al-baqarah/152'},
 {text:'Любимые для Аллаха слова: «Субханаллах, альхамдулиллях, ля иляха илляллах, Аллаху акбар». Муслим, 2137a.',source:'https://sunnah.com/muslim:2137a'}
];
const DHIKR_ACTIVITY_KEY='salah:dhikr-last-use-v1';
const DHIKR_DAY=86400000;
function dhikrTimestamp(value){return Number.isSafeInteger(value)&&value>0&&value<4102444800000?value:0;}
function normalizeDhikrReminder(value){return {enabled:value?.enabled===true,days:value?.days===2?2:3,time:'20:00',since:dhikrTimestamp(value?.since)};}
function readDhikrActivity(storage=globalThis.localStorage){try{return dhikrTimestamp(Number(storage.getItem(DHIKR_ACTIVITY_KEY)));}catch{return 0;}}
function markDhikrActivity(now=Date.now(),storage=globalThis.localStorage,target=globalThis.window){
 if(!dhikrTimestamp(now))return false;
 try{storage.setItem(DHIKR_ACTIVITY_KEY,String(Math.max(now,readDhikrActivity(storage))));target?.dispatchEvent(new Event('salah:dhikr-activity'));return true;}catch{return false;}
}
// The time refers to use of SALAH, never to a claim about worship outside the app.
function dhikrEventForDay(value,lastUse,day,zone,{localTimestamp,shiftDay,cityDay}){
 const row=normalizeDhikrReminder(value),baseline=Math.max(row.since,dhikrTimestamp(lastUse));
 if(!row.enabled||!baseline)return null;
 const threshold=baseline+row.days*DHIKR_DAY;
 let firstDay;try{firstDay=cityDay(threshold,zone);}catch{return null;}
 let firstAt=localTimestamp(firstDay,row.time,zone);
 if(!Number.isFinite(firstAt))return null;
 if(firstAt<threshold){firstDay=shiftDay(firstDay,1);firstAt=localTimestamp(firstDay,row.time,zone);}
 const dayGap=(Date.parse(day+'T12:00:00Z')-Date.parse(firstDay+'T12:00:00Z'))/DHIKR_DAY;
 if(!Number.isInteger(dayGap)||dayGap<0||dayGap%row.days!==0)return null;
 const at=localTimestamp(day,row.time,zone);
 if(!Number.isFinite(at)||at<threshold)return null;
 const slot=(dayGap/row.days)%DHIKR_MESSAGES.length;
 return {id:JSON.stringify(['dhikr',day,at]),day,kind:'dhikr',key:'return',phase:'at',at,adhan:false,message:DHIKR_MESSAGES[slot].text};
}

// Reminder scheduling is independent of the next-prayer display and browser APIs.
const PRAYER_KEYS = ['Fajr', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];
const BEFORE_MINUTES = [0, 5, 10, 15, 30];
const PRAYER_NAMES = {Fajr:'Фаджр',Dhuhr:'Зухр',Asr:'Аср',Maghrib:'Магриб',Isha:'Иша'};
const PRAYER_GENITIVE = {Fajr:'Фаджра',Dhuhr:'Зухра',Asr:'Асра',Maghrib:'Магриба',Isha:'Иша'};
const DAY = 86400000;

const reminderDefaults = {
  enabled:false, voice:'mansour', browserNotifications:false,
  prayers:Object.fromEntries(PRAYER_KEYS.map(key=>[key,{atTime:true,beforeMinutes:0,adhan:false}])),
  adhkar:{morning:{enabled:false,mode:'prayer',time:'07:00'},evening:{enabled:false,mode:'prayer',time:'18:00'}},
  jumuah:{enabled:false,time:'09:00'},
  tahajjud:{enabled:false},dhikr:normalizeDhikrReminder(null)
};

function validLocalTime(value){return typeof value==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(value);}

function normalizeReminders(value){
  const saved=value&&typeof value==='object'?value:{};
  const prayers=Object.fromEntries(PRAYER_KEYS.map(key=>{
    const row=saved.prayers?.[key]||{};
    const atTime=row.atTime===undefined?true:row.atTime===true;
    const before=typeof row.beforeMinutes==='number'||typeof row.beforeMinutes==='string'?Number(row.beforeMinutes):0;
    return [key,{atTime,beforeMinutes:BEFORE_MINUTES.includes(before)?before:0,adhan:atTime&&row.adhan===true}];
  }));
  const adhkar=Object.fromEntries(['morning','evening'].map(key=>{
    const row=saved.adhkar?.[key]||{};
    const mode=row.mode==='prayer'?'prayer':row.mode==='time'||validLocalTime(row.time)?'time':'prayer';
    return [key,{enabled:row.enabled===true,mode,time:validLocalTime(row.time)?row.time:reminderDefaults.adhkar[key].time}];
  }));
  return {enabled:saved.enabled===true,voice:saved.voice==='mishary'?'mishary':'mansour',browserNotifications:saved.browserNotifications===true,prayers,adhkar,jumuah:{enabled:saved.jumuah?.enabled===true,time:'09:00'},tahajjud:{enabled:saved.tahajjud?.enabled===true},dhikr:normalizeDhikrReminder(saved.dhikr)};
}

function shiftDay(day,amount){
  if(typeof day!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(day))return null;
  const time=Date.parse(day+'T12:00:00Z');
  if(!Number.isFinite(time)||new Date(time).toISOString().slice(0,10)!==day)return null;
  return new Date(time+amount*DAY).toISOString().slice(0,10);
}

function partsAt(time,zone){
  const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(time));
  return Object.fromEntries(parts.filter(part=>part.type!=='literal').map(part=>[part.type,part.value]));
}

// Resolve a wall-clock HH:mm in the selected city's zone; a skipped DST minute
// stays unavailable rather than being silently moved to another hour.
function localTimestamp(day,time,zone){
  if(!shiftDay(day,0)||!validLocalTime(time)||typeof zone!=='string'||!zone)return NaN;
  const [year,month,date]=day.split('-').map(Number),[hour,minute]=time.split(':').map(Number);
  const target=Date.UTC(year,month-1,date,hour,minute,0);
  let result=target;
  try{
    for(let attempt=0;attempt<4;attempt++){
      const p=partsAt(result,zone);
      const represented=Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day),Number(p.hour),Number(p.minute),Number(p.second));
      const correction=target-represented;
      result+=correction;
      if(correction===0)break;
    }
    const p=partsAt(result,zone);
    return p.year+'-'+p.month+'-'+p.day===day&&p.hour+':'+p.minute===time?result:NaN;
  }catch{return NaN;}
}

function timestamp(value){
  if(typeof value==='number')return Number.isFinite(value)?value:NaN;
  if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value))return Date.parse(value);
  return NaN;
}

function buildReminderEvents(value,context){
  const settings=normalizeReminders(value);
  if(!settings.enabled||!context?.cityKey||!shiftDay(context.today,0)||typeof context.timingsFor!=='function')return [];
  const dates=[shiftDay(context.today,-1),context.today,context.tomorrow||shiftDay(context.today,1)];
  const events=[];
  for(const day of new Set(dates.filter(Boolean))){
    let times;
    try{times=context.timingsFor(day)||{};}catch{times={};}
    for(const key of PRAYER_KEYS){
      const prayerAt=timestamp(times[key]);
      if(!Number.isFinite(prayerAt))continue;
      const row=settings.prayers[key];
      const phases=[];
      if(row.beforeMinutes>0)phases.push({phase:'before:'+row.beforeMinutes,at:prayerAt-row.beforeMinutes*60000,message:'До '+PRAYER_GENITIVE[key]+' осталось '+row.beforeMinutes+' минут',adhan:false});
      if(row.atTime)phases.push({phase:'at',at:prayerAt,message:'Наступило время '+PRAYER_GENITIVE[key],adhan:row.adhan});
      for(const phase of phases)events.push({...phase,id:JSON.stringify([String(context.cityKey),day,'prayer',key,prayerAt,phase.phase]),day,kind:'prayer',key,prayerAt});
    }
    for(const key of ['morning','evening']){
      const row=settings.adhkar[key];
      if(!row.enabled)continue;
      const at=row.mode==='prayer'?timestamp(times[key==='morning'?'Fajr':'Maghrib']):localTimestamp(day,row.time,context.timeZone);
      if(!Number.isFinite(at))continue;
      events.push({id:JSON.stringify([String(context.cityKey),day,'adhkar',key,at,'at']),day,kind:'adhkar',key,phase:'at',at,adhan:false,message:key==='morning'?'Время утренних азкаров':'Время вечерних азкаров'});
    }
    // Anchor to the night ending with this day's Fajr, even across a month or DST boundary.
    if(settings.tahajjud.enabled){
      let previous;try{previous=context.timingsFor(shiftDay(day,-1))||{};}catch{previous={};}
      const at=lastThirdNight(timestamp(previous.Maghrib),timestamp(times.Fajr));
      if(Number.isFinite(at))events.push({id:JSON.stringify([String(context.cityKey),day,'tahajjud',at,'at']),day,kind:'tahajjud',key:'tahajjud',phase:'at',at,adhan:false,message:'Тахаджуд: началась последняя треть ночи'});
    }
    // The city's calendar day determines Friday; prayer data is not required.
    if(settings.jumuah.enabled&&new Date(day+'T12:00:00Z').getUTCDay()===5){
      const at=localTimestamp(day,settings.jumuah.time,context.timeZone);
      if(Number.isFinite(at))events.push({id:JSON.stringify([String(context.cityKey),day,'jumuah',at,'at']),day,kind:'jumuah',key:'jumuah',phase:'at',at,adhan:false,message:'Сегодня Джума'});
    }
  }
  for(const day of new Set(dates.filter(Boolean))){
    const event=dhikrEventForDay(settings.dhikr,context.dhikrLastAt,day,context.timeZone,{localTimestamp,shiftDay,cityDay:(at,zone)=>{const p=partsAt(at,zone);return p.year+'-'+p.month+'-'+p.day;}});
    if(event)events.push(event);
  }
  return events.sort((a,b)=>a.at-b.at||a.id.localeCompare(b.id));
}

function createReminderTracker({read=()=>({}),write=()=>{},maxGap=65000,freshness=60000,retention=7*DAY}={}){
  let previous=null,remembered={};
  function mergeSeen(){
    try{
      const raw=read(),events=raw?.events||{};
      if(events&&typeof events==='object')for(const [id,at]of Object.entries(events))if(typeof at==='number'&&Number.isFinite(at))remembered[id]=at;
    }catch{}
  }
  mergeSeen();
  function reset(){previous=null;}
  function tick(now,events){
    if(!Number.isFinite(now))return [];
    const before=previous;previous=now;
    if(before===null||now<before||now-before>maxGap)return [];
    mergeSeen();
    const due=[];
    for(const event of events||[]){
      if(typeof event?.id!=='string'||!Number.isFinite(event.at)||event.at<=before||event.at>now||now-event.at>freshness||Object.hasOwn(remembered,event.id))continue;
      remembered[event.id]=event.at;due.push(event);
    }
    if(due.length){
      remembered=Object.fromEntries(Object.entries(remembered).filter(([,at])=>at>=now-retention));
      try{write({version:1,events:{...remembered}});}catch{}
    }
    return due;
  }
  return {tick,reset};
}



const PUSH_ORIGIN='https://skodytunez-maker.github.io';
const PUBLIC_APP=PUSH_ORIGIN+'/salah/';
const DAY_MS=86400000;
class PushError extends Error {constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new PushError(status,message);};
const object=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
async function digest(value){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),n=>n.toString(16).padStart(2,'0')).join('');}
function credentials(body){
 if(!object(body)||typeof body.id!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(body.id)||typeof body.token!=='string'||!/^[a-f0-9]{64}$/.test(body.token))fail(400,'Недопустимая подписка');
 return {id:body.id,token:body.token};
}
function base64Bytes(value,length){
 if(typeof value!=='string'||!/^[\w-]+$/.test(value)||value.length>100)fail(400,'Недопустимый ключ');
 let decoded;try{decoded=Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));}catch{fail(400,'Недопустимый ключ');}
 if(decoded.length!==length)fail(400,'Недопустимый ключ');return decoded;
}
function subscription(value){
 if(!object(value)||typeof value.endpoint!=='string'||value.endpoint.length>4096)fail(400,'Недопустимый адрес доставки');
 let url;try{url=new URL(value.endpoint);}catch{fail(400,'Недопустимый адрес доставки');}
 const host=url.hostname;
 // Only official browser push gateways may receive a server request (SSRF guard).
 if(url.protocol!=='https:'||url.port&&url.port!=='443'||url.username||url.password||url.hash||!((host==='web.push.apple.com')||(host==='fcm.googleapis.com')||(host==='updates.push.services.mozilla.com')||(/^[a-z0-9-]+\.notify\.windows\.com$/.test(host))))fail(400,'Недопустимый адрес доставки');
 if(!object(value.keys)||base64Bytes(value.keys.p256dh,65)[0]!==4)fail(400,'Недопустимый ключ');base64Bytes(value.keys.auth,16);
 return {endpoint:url.href,keys:{p256dh:value.keys.p256dh,auth:value.keys.auth}};
}
function preferences(value){
 if(!object(value)||!object(value.city))fail(400,'Выберите город');
 const c=value.city;
 if(typeof c.name!=='string'||!c.name.trim()||c.name.length>160||!Number.isFinite(c.latitude)||Math.abs(c.latitude)>90||!Number.isFinite(c.longitude)||Math.abs(c.longitude)>180||typeof c.timezone!=='string'||c.timezone.length>80)fail(400,'Недопустимый город');
 try{new Intl.DateTimeFormat('en',{timeZone:c.timezone}).format(0);}catch{fail(400,'Недопустимый часовой пояс');}
 if(![1,2,3,4,5,13].includes(value.method)||![0,1].includes(value.school)||![1,2,3].includes(value.highLatitude))fail(400,'Недопустимый расчёт');
 if(value.tyumenTimeSource!==undefined&&!TYUMEN_SOURCES.includes(value.tyumenTimeSource))fail(400,'Недопустимый источник расписания');
 const tyumenTimeSource=normalizeTyumenSource(value.tyumenTimeSource);
 const offsets={},tableOffsets={},mosqueTimes={};
 for(const key of PRAYER_KEYS){const n=value.offsets?.[key]??0;if(!Number.isInteger(n)||Math.abs(n)>60)fail(400,'Недопустимая поправка');offsets[key]=n;const tableN=value.tableOffsets?.[key]??0;if(!Number.isInteger(tableN)||Math.abs(tableN)>60)fail(400,'Недопустимая поправка');tableOffsets[key]=tableN;
  if(value.mosque===true){if(!validLocalTime(value.mosqueTimes?.[key]))fail(400,'Недопустимое личное расписание');mosqueTimes[key]=value.mosqueTimes[key];}}
 // Explicit allow-list: never store prayer history, counters, email or backups.
 const reminders=normalizeReminders(value.reminders);
 reminders.browserNotifications=false;
 return {city:{name:c.name.trim(),latitude:c.latitude,longitude:c.longitude,timezone:c.timezone},method:value.method,school:value.school,highLatitude:value.highLatitude,tyumenTimeSource,offsets,tableOffsets,mosque:value.mosque===true,mosqueTimes,reminders,...(reminders.enabled&&reminders.dhikr.enabled?{dhikrLastAt:dhikrTimestamp(value.dhikrLastAt)}:{})};
}
function cityDay(now,zone){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now));}
function isTyumen(p){return /^(Тюмень|Tyumen)$/i.test(p.city.name)&&Math.abs(p.city.latitude-57.1522)<.2&&Math.abs(p.city.longitude-65.5272)<.3;}
function serverTimings(day,rows,p){
 const row=rows[day];if(!row||isTyumen(p)&&!matchesTyumenSource(p.tyumenTimeSource,row))return null;
 const times={};for(const key of PRAYER_KEYS){
  let stamp=Date.parse(row.timings?.[key]);
  if(isTyumen(p)&&key==='Asr'&&p.school===0)stamp=firstAsrValid(day,row,row.asrFirst)?Date.parse(row.asrFirst):NaN;
  if(isTyumen(p))stamp+=p.tableOffsets?.[key]*60000||0;
  if(!isTyumen(p)){
   if(p.mosque)stamp=localTimestamp(day,p.mosqueTimes[key],p.city.timezone);
   stamp+=p.offsets[key]*60000;
  }
  times[key]=Number.isFinite(stamp)?stamp:null;
 }
 return times;
}
function eventsFor(p,rows,now){
 const today=cityDay(now,p.city.timezone);
 return buildReminderEvents(p.reminders,{today,cityKey:JSON.stringify([p.city.latitude,p.city.longitude,p.city.timezone,p.method,p.school,p.highLatitude,p.tyumenTimeSource,p.offsets,p.tableOffsets,p.mosque,p.mosqueTimes]),timeZone:p.city.timezone,dhikrLastAt:p.dhikrLastAt,timingsFor:day=>serverTimings(day,rows,p)});
}
function dueEvents(events,now){return events.filter(e=>e.at<=now&&now-e.at<90000);}
async function scheduleRows(p,now,{cache,fetcher=fetch}){
 const today=cityDay(now,p.city.timezone),dates=[shiftDay(today,-1),today,shiftDay(today,1)];
 let rows={};
 async function json(url){const response=await fetcher(url,{signal:AbortSignal.timeout(15000),redirect:'error'});if(!response.ok)throw Error('schedule-unavailable');return response.json();}
 if(isTyumen(p)){
  // Never invent a new Tyumen timetable when no approved local month exists.
  const key='tyumen-published-v2:'+normalizeTyumenSource(p.tyumenTimeSource),saved=await cache.get(key,now);
  if(saved)return saved;
  for(const file of tyumenSourceFiles(p.tyumenTimeSource)){const data=await json(PUBLIC_APP+'data/'+file);Object.assign(rows,data.days||{});}
  const supplement=await json(PUBLIC_APP+'data/tyumen-first-asr.json');
  rows=mergeFirstAsr(rows,supplement.days||{});
  await cache.put(key,rows,now+6*3600000);return rows;
 }
 for(const month of new Set(dates.map(d=>d.slice(0,7)))){
  const params=new URLSearchParams({latitude:String(p.city.latitude),longitude:String(p.city.longitude),method:String(p.method),school:String(p.school),latitudeAdjustmentMethod:String(p.highLatitude),iso8601:'true'});
  const key='aladhan:'+month+':'+await digest(params.toString());let saved=await cache.get(key,now);
  if(!saved){const data=await json('https://api.aladhan.com/v1/calendar/'+month.slice(0,4)+'/'+Number(month.slice(5,7))+'?'+params);
   if(!Array.isArray(data.data)||data.data.length>31)throw Error('schedule-invalid');saved={};
   for(const row of data.data){const day=row.date?.gregorian?.date?.split('-').reverse().join('-');
    if(!shiftDay(day,0)||!day.startsWith(month)||!PRAYER_KEYS.every(key=>typeof row.timings?.[key]==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(row.timings[key])&&Number.isFinite(Date.parse(row.timings[key]))))throw Error('schedule-invalid');
    saved[day]={timings:Object.fromEntries(PRAYER_KEYS.map(key=>[key,row.timings[key]]))};}
   await cache.put(key,saved,now+24*3600000);
  }
  Object.assign(rows,saved);
 }
 return rows;
}
function notification(event,now){return {title:'SALAH',body:event.message,tag:'salah-push-'+event.hash,url:['adhkar','dhikr'].includes(event.kind)?'#adhkar':'#home',at:event.at,expiresAt:event.at+120000};}
function needsPrayerTimings(p){return p.reminders.enabled&&(PRAYER_KEYS.some(key=>p.reminders.prayers[key].atTime||p.reminders.prayers[key].beforeMinutes>0)||Object.values(p.reminders.adhkar).some(row=>row.enabled&&row.mode==='prayer')||p.reminders.tahajjud.enabled);}
function createPushHandler({db,webpush,fetcher=fetch,clock=Date.now}){
 async function send(device,event){
  try{const now=clock();await webpush.sendNotification(device.subscription,JSON.stringify(notification(event,now)),{vapidDetails:{subject:PUBLIC_APP,publicKey:(await db.config()).vapid.publicKey,privateKey:(await db.config()).vapid.privateKey},TTL:Math.max(1,Math.ceil((event.at+120000-now)/1000)),urgency:event.kind==='dhikr'?'normal':'high',timeout:8000});return 'sent';}
  catch(error){if([404,410].includes(error.statusCode)){await db.expire(device.id);return 'expired';}return 'retry';}
 }
 return async function handle(request){
  const origin=request.headers.get('Origin'),action=new URL(request.url).pathname.split('/').pop();
  const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin'};
  if(origin===PUSH_ORIGIN){headers['Access-Control-Allow-Origin']=origin;headers['Access-Control-Allow-Headers']='Content-Type';headers['Access-Control-Allow-Methods']='GET, POST, OPTIONS';}
  const reply=(value,status=200)=>new Response(JSON.stringify(value),{status,headers});
  try{
   if(origin&&origin!==PUSH_ORIGIN)fail(403,'Этот адрес не разрешён');
   if(request.method==='OPTIONS'){if(origin!==PUSH_ORIGIN)fail(403,'Этот адрес не разрешён');return new Response(null,{status:204,headers});}
   if(action==='config'&&request.method==='GET'){const config=await db.ensureConfig(()=>webpush.generateVAPIDKeys());return reply({version:1,remindersVersion:3,features:['tahajjud','dhikr-inactivity'],publicKey:config.vapid.publicKey});}
   if(action==='dispatch'&&request.method==='POST'){
    const config=await db.config(),secret=request.headers.get('X-Salah-Cron');
    if(!secret||await digest(secret)!==await digest(config.cron_secret))fail(401,'Доступ запрещён');
    if(!await db.lease(clock()))return reply({busy:true});
    let delivered=0;
    try{
     const devices=await db.active(clock()),grouped=new Map(),started=clock();let cursor=0;
     async function deliverDevice(device){
      const p=preferences(device.preferences),signature=JSON.stringify(p);
      if(!grouped.has(signature))grouped.set(signature,(needsPrayerTimings(p)?scheduleRows(p,clock(),{cache:db.cache,fetcher}).catch(()=>({})):Promise.resolve({})).then(rows=>eventsFor(p,rows,clock())));
      const events=await grouped.get(signature);
      for(const event of dueEvents(events,clock())){
       if(event.kind==='dhikr'){
        // A resumed reader or an opt-out during timetable fetching must cancel this send.
        const fresh=await db.get(device.id);if(!fresh)continue;
        const latest=preferences(fresh.preferences);
        if(!eventsFor(latest,{},clock()).some(e=>e.kind==='dhikr'&&e.at===event.at))continue;
        const previous=await db.lastDhikrSent(device.id);
        if(previous&&clock()-previous<(latest.reminders.dhikr.days*24-2)*3600000)continue;
       }
       const hash=(event.kind==='dhikr'?'dhikr-':'')+await digest(JSON.stringify([event.day,event.kind,event.key,event.phase,event.at]));if(!await db.claim(device.id,hash,event.at,clock()))continue;
       const result=await send(device,{...event,hash});await db.complete(device.id,hash,result);if(result==='sent')delivered++;
       if(result==='expired')break;
      }
     }
     // A dead push gateway must not hold up all other phones.
     await Promise.all(Array.from({length:Math.min(8,devices.length)},async()=>{while(cursor<devices.length&&clock()-started<95000){const device=devices[cursor++];await deliverDevice(device);}}));
     await db.cleanup(clock());return reply({delivered});
    }finally{await db.release();}
   }
   if(!['subscribe','unsubscribe','test'].includes(action)||request.method!=='POST')fail(404,'Не найдено');
   if(origin!==PUSH_ORIGIN)fail(403,'Этот адрес не разрешён');
   if(Number(request.headers.get('Content-Length')||0)>8192)fail(413,'Слишком много данных');
   const reader=request.body?.getReader();if(!reader)fail(400,'Недопустимые данные');const chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>8192){await reader.cancel();fail(413,'Слишком много данных');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}const text=new TextDecoder().decode(bytes);
   let body;try{body=JSON.parse(text);}catch{fail(400,'Недопустимые данные');}
   const auth=credentials(body),tokenHash=await digest(auth.token);
   if(!await db.rate('global:'+action,action==='subscribe'?180:60,clock()))fail(429,'Попробуйте немного позже');
   const device=await db.get(auth.id);
   if(device&&device.token_hash!==tokenHash)fail(403,'Доступ запрещён');
   if(!await db.rate(auth.id+':'+action,action==='subscribe'?10:1,clock()))fail(429,'Попробуйте через минуту');
   if(action==='subscribe'){
    const sub=subscription(body.subscription),p=preferences(body.preferences),endpointHash=await digest(sub.endpoint);
    await db.ensureConfig(()=>webpush.generateVAPIDKeys());
    if(!device&&!await db.rate('new-devices',20,clock()))fail(429,'Попробуйте немного позже');
    if(!device){const peer=request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';if(!await db.rate('new-peer:'+await digest(peer),10,clock()))fail(429,'Попробуйте через минуту');}
    if(!device&&await db.count()>=1000)fail(503,'Доставка временно недоступна');
    if(p.reminders.dhikr.enabled){p.reminders.dhikr.since=Math.min(p.reminders.dhikr.since||clock(),clock());p.dhikrLastAt=Math.min(p.dhikrLastAt||0,clock());
     if(device?.preferences?.reminders?.dhikr?.enabled===true)p.dhikrLastAt=Math.max(p.dhikrLastAt,Math.min(dhikrTimestamp(device.preferences.dhikrLastAt),clock()));}
    const needsSchedule=needsPrayerTimings(p);
    const rows=needsSchedule?await scheduleRows(p,clock(),{cache:db.cache,fetcher}):{};
    const today=cityDay(clock(),p.city.timezone),ready=PRAYER_KEYS.every(key=>Number.isFinite(serverTimings(today,rows,p)?.[key]));
    if(needsSchedule&&!ready)fail(503,'На эту дату нет проверенного расписания');
    if(!device){const welcome={hash:'connected-'+clock(),at:clock(),kind:'test',message:'Фоновые уведомления SALAH подключены.'};if(await send({id:auth.id,subscription:sub},welcome)!=='sent')fail(400,'Телефон не подтвердил доставку. Повторите подключение.');}
    await db.upsert({id:auth.id,token_hash:tokenHash,endpoint_hash:endpointHash,subscription:sub,preferences:p,now:clock()});
    return reply({saved:true,enabled:p.reminders.enabled});
   }
   if(!device)fail(404,'Подписка не найдена');
   if(action==='unsubscribe'){await db.remove(auth.id);return reply({removed:true});}
   const event={hash:'test-'+clock(),at:clock(),kind:'test',message:'Фоновые уведомления SALAH подключены.'};
   if(await send(device,event)!=='sent')fail(503,'Не удалось доставить проверку');
   return reply({sent:true});
  }catch(error){return reply({error:error instanceof PushError?error.message:'Сервис доставки временно недоступен'},error instanceof PushError?error.status:503);}
 };
}

const sql=postgres(Deno.env.get('SUPABASE_DB_URL'),{max:1,idle_timeout:20,connect_timeout:10,prepare:false});
const db={
 async config(){const [row]=await sql`select vapid,cron_secret from salah_push_private.config where id=1`;return row;},
 async ensureConfig(generate){let row=await this.config();if(!row)throw Error('migration-required');if(!row.vapid){const keys=generate();await sql`update salah_push_private.config set vapid=${sql.json(keys)} where id=1 and vapid is null`;row=await this.config();}return row;},
 async get(id){const [row]=await sql`select id,token_hash,subscription,preferences from salah_push_private.devices where id=${id}::uuid`;return row;},
 async count(){const [row]=await sql`select count(*)::int as n from salah_push_private.devices`;return row.n;},
 async upsert(d){await sql`insert into salah_push_private.devices(id,token_hash,endpoint_hash,subscription,preferences,updated_at,enabled) values(${d.id}::uuid,${d.token_hash},${d.endpoint_hash},${sql.json(d.subscription)},${sql.json(d.preferences)},to_timestamp(${d.now}/1000.0),${d.preferences.reminders.enabled}) on conflict(id) do update set endpoint_hash=excluded.endpoint_hash,subscription=excluded.subscription,preferences=excluded.preferences,updated_at=excluded.updated_at,enabled=excluded.enabled where salah_push_private.devices.token_hash=excluded.token_hash`;},
 async remove(id){await sql`delete from salah_push_private.devices where id=${id}::uuid`;},
 async expire(id){await sql`update salah_push_private.devices set enabled=false,subscription=null,preferences=null where id=${id}::uuid`;},
 async active(now){return sql`select id,subscription,preferences from salah_push_private.devices where enabled=true and subscription is not null and preferences is not null and updated_at>to_timestamp(${now}/1000.0)-interval '90 days'`;},
 async lastDhikrSent(id){const [row]=await sql`select extract(epoch from max(event_at))*1000 as at from salah_push_private.deliveries where device_id=${id}::uuid and event_hash like 'dhikr-%' and state='sent'`;return Number(row?.at)||0;},
 async rate(key,limit,now){const minute=Math.floor(now/60000);const rows=await sql`insert into salah_push_private.limits(key,minute,n) values(${key},${minute},1) on conflict(key,minute) do update set n=salah_push_private.limits.n+1 returning n`;return rows[0].n<=limit;},
 async lease(now){const rows=await sql`update salah_push_private.config set lease_until=to_timestamp(${now}/1000.0)+interval '150 seconds' where id=1 and (lease_until is null or lease_until<to_timestamp(${now}/1000.0)) returning id`;return rows.length===1;},
 async release(){await sql`update salah_push_private.config set lease_until=null where id=1`;},
 async claim(id,hash,at,now){const rows=await sql`insert into salah_push_private.deliveries(device_id,event_hash,event_at,state,claimed_at) values(${id}::uuid,${hash},to_timestamp(${at}/1000.0),'sending',to_timestamp(${now}/1000.0)) on conflict(device_id,event_hash) do update set state='sending',claimed_at=excluded.claimed_at where salah_push_private.deliveries.state='retry' or (salah_push_private.deliveries.state='sending' and salah_push_private.deliveries.claimed_at<to_timestamp(${now}/1000.0)-interval '30 seconds') returning event_hash`;return rows.length===1;},
 async complete(id,hash,state){await sql`update salah_push_private.deliveries set state=${state} where device_id=${id}::uuid and event_hash=${hash}`;},
 async cleanup(now){await sql`delete from salah_push_private.deliveries where event_at<to_timestamp(${now}/1000.0)-interval '7 days'`;await sql`delete from salah_push_private.limits where minute<${Math.floor(now/60000)-1440}`;await sql`delete from salah_push_private.cache where expires_at<to_timestamp(${now}/1000.0)-interval '2 days'`;await sql`delete from salah_push_private.devices where updated_at<to_timestamp(${now}/1000.0)-interval '90 days'`;},
 cache:{
  async get(key,now){const [row]=await sql`select rows from salah_push_private.cache where key=${key} and expires_at>to_timestamp(${now}/1000.0)`;return row?.rows;},
  async put(key,rows,expires){await sql`insert into salah_push_private.cache(key,rows,expires_at) values(${key},${sql.json(rows)},to_timestamp(${expires}/1000.0)) on conflict(key) do update set rows=excluded.rows,expires_at=excluded.expires_at`;}
 }
};
Deno.serve(createPushHandler({db,webpush}));
